# Clonamos el repositorio para obtener los dataSet

In [ ]:
!git clone https://github.com/joanby/machinelearning-az.git

# Damos acceso a nuestro Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Test it

In [ ]:
!ls '/content/drive/My Drive' 

# Google colab tools

In [ ]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

# Instalar dependendias

In [ ]:
!pip install sklearn

# Natural Language Processing

# Cómo importar las librerías


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (16, 9)
plt.style.use('ggplot')
from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from IPython.display import Image as PImage
from subprocess import check_call
from PIL import Image, ImageDraw, ImageFont

# Importar el data set


In [3]:
dataset = pd.read_csv("Restaurant_Reviews.tsv", delimiter = "\t", quoting = 3)

# Limpieza de texto

In [4]:
import re
import nltk
# nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

# Crear el Bag of Words

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, 1].values

# Dividir el data set en conjunto de entrenamiento y conjunto de testing

In [60]:
from sklearn.model_selection import train_test_split

In [100]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)

# Ajustar el clasificador en el Conjunto de Entrenamiento

In [7]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred  = classifier.predict(X_test)

# Elaborar una matriz de confusión

In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)
tp = cm[0,[0]]
tn = cm[1,[1]]
fn = cm[1,[0]]
fp = cm[0,[1]]

[[ 83  60]
 [ 26 131]]


In [25]:
accu = (tp+tn)/(tp+tn+fn+fp)
pre = tp/(tp+fp)
rec = tp/(tp+fn)
F1 = 2*pre*rec/(pre+rec)

print('Naive Bayes:', 'Accuracy:',accu, 'Precision:',pre, 'Recall:',rec, 'F1:',F1)

Naive Bayes: Accuracy: [0.71333333] Precision: [0.58041958] Recall: [0.76146789] F1: [0.65873016]


array([26])

### Logistic regression

In [26]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

y_pred  = classifier.predict(X_test)

In [27]:
cm = confusion_matrix(y_test, y_pred)

print(cm)
tp = cm[0,[0]]
tn = cm[1,[1]]
fn = cm[1,[0]]
fp = cm[0,[1]]

[[117  26]
 [ 60  97]]


In [28]:
accu = (tp+tn)/(tp+tn+fn+fp)
pre = tp/(tp+fp)
rec = tp/(tp+fn)
F1 = 2*pre*rec/(pre+rec)

print('Logistic:', 'Accuracy:',accu, 'Precision:',pre, 'Recall:',rec, 'F1:',F1)

Logistic: Accuracy: [0.71333333] Precision: [0.81818182] Recall: [0.66101695] F1: [0.73125]


### KNN

In [32]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = "minkowski", p = 2)
classifier.fit(X_train, y_train)

y_pred  = classifier.predict(X_test)

In [33]:
cm = confusion_matrix(y_test, y_pred)

print(cm)
tp = cm[0,[0]]
tn = cm[1,[1]]
fn = cm[1,[0]]
fp = cm[0,[1]]

[[107  36]
 [ 67  90]]


In [34]:
accu = (tp+tn)/(tp+tn+fn+fp)
pre = tp/(tp+fp)
rec = tp/(tp+fn)
F1 = 2*pre*rec/(pre+rec)

print('KNN:', 'Accuracy:',accu, 'Precision:',pre, 'Recall:',rec, 'F1:',F1)

KNN: Accuracy: [0.65666667] Precision: [0.74825175] Recall: [0.61494253] F1: [0.67507886]


### SVM

In [65]:
from sklearn.svm import SVC
classifier = SVC(kernel = "linear", random_state = 0)
classifier.fit(X_train, y_train)

y_pred  = classifier.predict(X_test)

In [67]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)
tp = cm[0,[0]]
tn = cm[1,[1]]
fn = cm[1,[0]]
fp = cm[0,[1]]

[[111  32]
 [ 52 105]]


In [68]:
accu = (tp+tn)/(tp+tn+fn+fp)
pre = tp/(tp+fp)
rec = tp/(tp+fn)
F1 = 2*pre*rec/(pre+rec)

print('SVC Linear:', 'Accuracy:',accu, 'Precision:',pre, 'Recall:',rec, 'F1:',F1)

SVC Linear: Accuracy: [0.72] Precision: [0.77622378] Recall: [0.6809816] F1: [0.7254902]


### SVM RADIAL

In [69]:
classifier = SVC(kernel = "rbf", random_state = 0)
classifier.fit(X_train, y_train)

y_pred  = classifier.predict(X_test)

In [70]:
cm = confusion_matrix(y_test, y_pred)

print(cm)
tp = cm[0,[0]]
tn = cm[1,[1]]
fn = cm[1,[0]]
fp = cm[0,[1]]

[[132  11]
 [ 73  84]]


In [71]:
accu = (tp+tn)/(tp+tn+fn+fp)
pre = tp/(tp+fp)
rec = tp/(tp+fn)
F1 = 2*pre*rec/(pre+rec)

print('SVC Radial:', 'Accuracy:',accu, 'Precision:',pre, 'Recall:',rec, 'F1:',F1)

SVC Radial: Accuracy: [0.72] Precision: [0.92307692] Recall: [0.64390244] F1: [0.75862069]


### Decision Tree

In [72]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = "entropy")
classifier.fit(X_train, y_train)

y_pred  = classifier.predict(X_test)

In [73]:
cm = confusion_matrix(y_test, y_pred)

print(cm)
tp = cm[0,[0]]
tn = cm[1,[1]]
fn = cm[1,[0]]
fp = cm[0,[1]]

[[116  27]
 [ 62  95]]


In [75]:
accu = (tp+tn)/(tp+tn+fn+fp)
pre = tp/(tp+fp)
rec = tp/(tp+fn)
F1 = 2*pre*rec/(pre+rec)

print('Decision Tree:', 'Accuracy:',accu, 'Precision:',pre, 'Recall:',rec, 'F1:',F1)

Decision Tree: Accuracy: [0.70333333] Precision: [0.81118881] Recall: [0.65168539] F1: [0.72274143]


### Random Forest

In [83]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 5, criterion = "entropy")
classifier.fit(X_train, y_train)

y_pred  = classifier.predict(X_test)

In [84]:
cm = confusion_matrix(y_test, y_pred)

print(cm)
tp = cm[0,[0]]
tn = cm[1,[1]]
fn = cm[1,[0]]
fp = cm[0,[1]]

[[103  40]
 [ 43 114]]


In [85]:
accu = (tp+tn)/(tp+tn+fn+fp)
pre = tp/(tp+fp)
rec = tp/(tp+fn)
F1 = 2*pre*rec/(pre+rec)

print('Random Forest:', 'Accuracy:',accu, 'Precision:',pre, 'Recall:',rec, 'F1:',F1)

Random Forest: Accuracy: [0.72333333] Precision: [0.72027972] Recall: [0.70547945] F1: [0.71280277]


### CART

In [33]:
XT = pd.DataFrame(X)
XT['y'] = pd.DataFrame(y)
XT.head()

0  1  2  3  4  5  6  7  8  9  ...  1491  1492  1493  1494  1495  1496  \
0  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
1  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
2  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
3  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
4  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   

   1497  1498  1499  y  
0     0     0     0  1  
1     0     0     0  0  
2     0     0     0  0  
3     0     0     0  1  
4     0     0     0  1  

[5 rows x 1501 columns]

In [37]:

cv = KFold(n_splits=5) # Numero deseado de "folds" que haremos
accuracies = list()
depth_range = range(1, 16)
 
# Testearemos la profundidad de 1 a cantidad de atributos +1
for depth in depth_range:
    fold_accuracy = []
    tree_model = tree.DecisionTreeClassifier(criterion='entropy',
                                             min_samples_split=20,
                                             min_samples_leaf=5,
                                             max_depth = depth,
                                             class_weight={1:3.5})
    for train_fold, valid_fold in cv.split(XT):
        f_train = XT.loc[train_fold] 
        f_valid = XT.loc[valid_fold] 
 
        model = tree_model.fit(X = f_train.drop(['y'], axis=1),y = f_train['y'])
        valid_acc = model.score(X = f_train.drop(['y'], axis= 1), y = f_train['y']) # calculamos la precision con el segmento de validacion
        fold_accuracy.append(valid_acc)
 
    avg = sum(fold_accuracy)/len(fold_accuracy)
    accuracies.append(avg)
    
# Mostramos los resultados obtenidos
df = pd.DataFrame({"Max Depth": depth_range, "Average Accuracy": accuracies})
df = df[["Max Depth", "Average Accuracy"]]
print(df.to_string(index=False))

 Max Depth  Average Accuracy
         1           0.50000
         2           0.50725
         3           0.51050
         4           0.51700
         5           0.51700
         6           0.52375
         7           0.53525
         8           0.54375
         9           0.54625
        10           0.54875
        11           0.54875
        12           0.56150
        13           0.56325
        14           0.56700
        15           0.57300


In [57]:
# Crear arrays de entrenamiento y las etiquetas que indican si llegó a top o no 
y_train = XT['y']
x_train = XT.drop(['y'], axis=1).values 
 
# Crear Arbol de decision con profundidad = 4
decision_tree = tree.DecisionTreeClassifier(criterion='entropy',
                                            min_samples_split=15,
                                            min_samples_leaf=5,
                                            max_depth = 15,
                                            class_weight={1:3.5})
decision_tree.fit(x_train, y_train)
 
acc_decision_tree = round(decision_tree.score(x_train, y_train) * 100, 2)
print(acc_decision_tree)

55.9


In [101]:
decision_tree.fit(X_train, y_train)
y_pred  = classifier.predict(X_test)

In [102]:
cm = confusion_matrix(y_test, y_pred)

print(cm)
tp = cm[0,[0]]
tn = cm[1,[1]]
fn = cm[1,[0]]
fp = cm[0,[1]]

[[103  40]
 [ 43 114]]


In [103]:
accu = (tp+tn)/(tp+tn+fn+fp)
pre = tp/(tp+fp)
rec = tp/(tp+fn)
F1 = 2*pre*rec/(pre+rec)

print('CART:', 'Accuracy:',accu, 'Precision:',pre, 'Recall:',rec, 'F1:',F1)

CART: Accuracy: [0.72333333] Precision: [0.72027972] Recall: [0.70547945] F1: [0.71280277]
